### ISSUE TITLE
master vs hydro-devel

### ISSUE THREAD

**Issue by davetcoleman** [ahornung/hrl_kinematics#1]
Hi, thanks for sharing this great code.

If I am interested in contributing to this library, should I be working on master on hydro-devel? I will definitely be using catkin, so I guess the answer is obviously hydro-devel, but what is the status of the `master` branch? Should it be removed?

Thanks!

**Comment by ahornung** [comment]
Thanks for your interest! Indeed, hydro-devel should be the default branch. I changed the setting now and deleted master.
